### ISSUE TITLE
add link (wysiwyg) not working in IE

### ISSUE THREAD

**Issue by adrigen** [collective/collective.github.com#820] opened 2015-03-05 02:52 UTC
Tried to add this on trac, but didn't have a login. 

Twice I have seen users try to add links in IE and the link button does nothing. The most recent instance was in IE11, but I can not replicate this issue on my testing VM. Does this sound familiar?

**Comment by vangheem** [comment] 2015-03-05 02:59
http://plone.293351.n2.nabble.com/TinyMCE-incompatibility-with-IE-11-td7572251.html

**Comment by vangheem** [comment] 2015-03-05 03:04
please report in: https://github.com/plone/Products.TinyMCE

The X-UA-COMPATIBLE header is set in plonetheme.sunburst and I'm not sure it's a safe thing to switch just to fix tinymce.

I wonder if there is a patch for tinymce. I also wonder if it is a minor release difference in IE11 since you also can not reproduce with a testing VM.

I'm going to close this for now. Again, please report in https://github.com/plone/Products.TinyMCE and then reference this ticket.

**Closed by vangheem** 2015-03-05 03:04 UTC
